# Generated by Django 5.0.3 on 2024-03-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_', '0003_product_category_product_subcategory_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('RE', 'Real Estate'), ('TR', 'Transport'), ('J', 'Job'), ('EL', 'Electronics')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('AP', 'Apartments'), ('H', 'Houses'), ('POF', 'Plot Of Land'), ('G', 'Garages'), ('C', 'Cars'), ('CP', 'Car Parts'), ('TR', 'Trucks'), ('PL', 'Planes'), ('TRA', 'Trade'), ('RPC', 'Restaurants, Pubs, Cafes'), ('TD', 'Transport, Driver'), ('FS', 'Fitness, Sport'), ('BS', 'BabySitting'), ('CP', 'Cell Phones'), ('LT', 'Laptops'), ('MON', 'Monitors'), ('TV', 'TVs'), ('PS', 'Printers, Scanners'), ('CAM', 'Cameras')], max_length=60),
        ),
    ]
