# Generated by Django 5.0.3 on 2024-03-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_', '0005_product_image_alter_product_category_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
